import test from 'node:test';
import assert from 'node:assert/strict';
import { evaluateQualifiedInput } from '../skills/sales-lead-qualification/scripts/evaluate-qualified-input.mjs';

const fixture = () => {
  const observations = [{ criterion_id: 'need', org_id: 'org:test', subject_ref: 'subject:1', source_authority_ref: 'source:1', current: true, status: 'OBSERVED', score: 0.75, evidence_ref: 'evidence:1', source_version: 'r1' }];
  return { request: { org_id: 'org:test', subject_ref: 'subject:1', criteria_ref: 'criteria:1', criteria_version: '1', observations }, context: { authenticated: true, current: true, consumer: 'sales', action: 'sales.lead-qualification', purpose: 'qualification', org_id: 'org:test', subject_ref: 'subject:1', criteria: { accepted: true, ref: 'criteria:1', version: '1', acceptance_ref: 'acceptance:1', fields: [{ id: 'need', weight: 1 }, { id: 'timing', weight: 1 }] }, source_authority_ref: 'source:1', readable_fields: ['need', 'timing'], observations } };
};
test('accepted evidence yields a proposal score with unknowns preserved', () => { const { request, context } = fixture(); const result = evaluateQualifiedInput(request, context); assert.equal(result.score, 0.75); assert.equal(result.coverage, 0.5); assert.equal(result.evidence[1].status, 'UNKNOWN'); assert.equal(result.competent_acceptance, false); assert.equal(result.external_effects, false); assert.equal(result.state_mutated, false); });
test('current authentication, exact criteria, subject, purpose and authorized fields are required', () => { for (const patch of [{ authenticated: false }, { current: false }, { consumer: 'other' }, { action: 'unrelated' }, { subject_ref: 'other' }, { criteria: { accepted: false } }, { readable_fields: [] }, { source_authority_ref: '' }, { observations: [] }]) { const { request, context } = fixture(); assert.throws(() => evaluateQualifiedInput(request, { ...context, ...patch })); } });
test('request criteria drift, stale or unsupported observations cannot grant acceptance', () => { const { request, context } = fixture(); assert.throws(() => evaluateQualifiedInput({ ...request, criteria_version: 'old' }, context)); const stale = [{ ...request.observations[0], current: false }]; assert.throws(() => evaluateQualifiedInput({ ...request, observations: stale }, { ...context, observations: stale }), /OBSERVATION_SCOPE_INVALID/); const duplicate = [...request.observations, ...request.observations]; assert.throws(() => evaluateQualifiedInput({ ...request, observations: duplicate }, { ...context, observations: duplicate }), /DUPLICATE/); });
